### ISSUE TITLE
pdml2json

### ISSUE THREAD

**Issue by t-moe** [Enteee/pdml2flow#1]
It should be possible to disable the flow aggregation.
pdml2flow would then simply convert the xml to a json representation (as fluentflow did).

**Comment by Enteee** [comment]
How will the output look like when flow aggregation is disabled? I don't lake changing the output format. And you can easily get one packet per flow by doing a:

``` bash
$ pdml2flow -f frame.number | fluentflow __Flow_frames
```

I could introduce a new option which is basically a alias for -f frame.number. But do you really need this?

**Comment by t-moe** [comment]
Idea: introduce a new binary which behaves like pdml2flow but:
- does no flow aggregation & timeouting `-f frame.number -t0` 
- has no toplevel metadata
- does no deep-merge  `-a`
