### ISSUE TITLE
Better document use case

### ISSUE THREAD

**Issue by pocc** [Enteee/pdml2flow#15]
Why not use `tshark -T json`?

Tshark already has the ability to output json. Once you have json, you could use some utility to convert JSON to XML.

Whatever the reason, this issue is to provide better use case documentation in the README.

**Comment by Enteee** [comment]
Hello and thank you for your comment. I understand that `tshark` these days implements JSON-output. Which is indeed very powerful, but does not solve the `pdml2flow` use case. `pdml2flow` does implement flow aggregation. This means, all frames sharing certain characteristics, like same source and destination ip, are grouped together. These groups of frames are then being provided to the plugin layer in one callback. See the the `flow_*` callbacks [in the plugin interface](https://github.com/Enteee/pdml2flow#interface).

On top of that, the ability to write wireshark plugins in python enabled me to bootstrap and prototype new packet processing functionality within minutes.

All this is what I tried to capture in the first paragraph of the README:

> When analyzing network traffic, it is sometimes helpful to group captured frames. For example by port numbers to obtain network flows or using MAC addresses for hardware flows. Doing this in Wireshark or tshark is difficult. `pdml2flow` was designed to solve this use case. pdml2flow reads tshark output using the Packet Description Markup Language and writes flows either in JSON or XML. These flows are also accessible from a python plugin interface. If flow aggregation is not needed, `pdml2frame` can be be used to process pdml with plugins.

But I do understand that this section needs to make a clear point on how this is different from `tshark -T json`, I will add that.

**Comment by Enteee** [comment]
What do you think about the following?

> When analyzing network traffic, we can either inspect each frame individually or analyze groups  of captured frames. Such groups of frames are called flows. For example, grouping by port numbers gives us network flows. Network flows are helpful if we want to analyze communication behavior between applications. On the other hand if we group by MAC addresses, we obtain hardware flows. Those are interesting for debugging switching and trunking.
>
> Doing this in Wireshark or tshark is difficult. `pdml2flow` was designed to solve this use case. `pdml2flow` reads `tshark` output using the Packet Description Markup Language and writes flows either in JSON or XML. Using the [`-f` option](https://github.com/Enteee/pdml2flow#usage), one can simply change the flow definition. Furthermore, [plugins written in python](https://github.com/Enteee/pdml2flow#plugins) do have access to the frames and flows and implement custom flow processing logic. With [`pdml2flow-new-plugin`](https://github.com/Enteee/pdml2flow#create-a-new-plugin) bootstrapping a new plugin is only a matter of seconds. If flow aggregation is not needed, [`pdml2frame`](https://github.com/Enteee/pdml2flow#pdml2frame) enables python powered frame processing.

**Comment by pocc** [comment]
Much better written, cheers. I would add this as well as a 

```
## Similar Tools

* `tshark -T json` is good for X, pdml2flow does Y better
* [PyShark](https://kiminewt.github.io/pyshark/) is good for X, pdml2flow does Y better
```

Having a comparisons section demonstrates the maturity of your project :)

**Comment by Enteee** [comment]
Linking similar tools is a great idea. I'll do some research and try to find more entries for that section.
